# Generated by Django 5.2.5 on 2025-08-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spycats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bread',
            new_name='Breed',
        ),
        migrations.RenameField(
            model_name='spycat',
            old_name='bread',
            new_name='breed',
        ),
    ]
